FOOTBALL_LOCKS_TEAM_MAPPING = {
    "arizona": "ari",
    "atlanta": "atl",
    "baltimore": "bal",
    "buffalo": "buf",
    "carolina": "car",
    "chicago": "chi",
    "cincinnati": "cin",
    "cleveland": "cle",
    "dallas": "dal",
    "denver": "den",
    "detroit": "det",
    "green bay": "gb",
    "houston": "hou",
    "indianapolis": "ind",
    "jacksonville": "jac",
    "kansas city": "kan",
    "la chargers": "lac",
    "la rams": "lar",
    "las vegas": "lv",
    "miami": "mia",
    "minnesota": "min",
    "new england": "ne",
    "new orleans": "no",
    "ny giants": "nyg",
    "ny jets": "nyj",
    "pittsburgh": "pit",
    "philadelphia": "phi",
    "san francisco": "sfo",
    "seattle": "sea",
    "tampa bay": "tam",
    "tennessee": "ten",
    "washington": "was",
}

START_SIT_MAPPING = {
    "A+": 4.33,
    "A": 4.0,
    "A-": 3.66,
    "B+": 3.33,
    "B": 3.0,
    "B-": 2.66,
    "C+": 2.33,
    "C": 2.0,
    "D+": 1.66,
    "D": 1.33,
    "D-": 1.0,
    "F": 0,
}

FANTASY_PROS_TEAM_MAPPING = {
    "ARI": "ari",
    "ATL": "atl",
    "BAL": "bal",
    "BUF": "buf",
    "CAR": "car",
    "CHI": "chi",
    "CIN": "cin",
    "CLE": "cle",
    "DAL": "dal",
    "DEN": "den",
    "DET": "det",
    "FA": "fa",  # free agent
    "GB": "gb",
    "HOU": "hou",
    "IND": "ind",
    "JAC": "jac",
    "KC": "kan",
    "LAC": "lac",
    "LAR": "lar",
    "LV": "lv",
    "MIA": "mia",
    "MIN": "min",
    "NE": "ne",
    "NO": "no",
    "NYG": "nyg",
    "NYJ": "nyj",
    "PIT": "pit",
    "PHI": "phi",
    "SF": "sfo",
    "SEA": "sea",
    "TB": "tam",
    "TEN": "ten",
    "WAS": "was",
}
